### ISSUE TITLE
unable to find babylon parser

### ISSUE THREAD

**Issue by sunil1293** [nikaspran/coffee-to-ts#1]
While executing the command giving the following exception: 
coffee-to-ts ....

Error: Cannot find module 'babylon/lib/parser'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-to-ts/lib/babel/loadPlugins.js:9:15)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-to-ts/lib/jsToTs.js:3:20)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-to-ts/lib/index.js:7:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-to-ts/bin/coffee-to-ts.js:3:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

**Comment by bdeitte** [comment]
It looks like this is due to changes in babel, at least according to my quick reading of https://github.com/babel/babel/issues/3957

I didn't try to solve this myself- just curious on this project, wasn't sure if I was going to use it.  I would assume it would be solvable by just locking down some deps to an older version, like in the ticket above.

**Comment by vecernik** [comment]
+1

**Comment by reco** [comment]
+1

somebody managed to run this?

**Comment by franklin-ross** [comment]
I've got a working fork here: https://github.com/franklin-ross/coffee-to-ts

All I did was remove the carat from the babylon dependencies to fix the versions that get pulled down.

TBH I don't know how to make that fork into a PR for this repo, but the fix is super simple anyway.

**Comment by nikaspran** [comment]
My bad - totally missed the notifications on this!

Great catch regarding babel versions @bdeitte. I've adapted your PR a little bit @franklin-ross and the issue should now be fixed via https://github.com/nikaspran/coffee-to-ts/commit/d1dcd10a42eff20092698450de1070e91b895997

I've now enabled the notifications again so let me know if there are any further issues.
